"""Generate/check the schema-v2 MCP tool reference from capability_map.json."""

from __future__ import annotations

import argparse
import os
import tempfile
from pathlib import Path
from typing import Any

import json

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CATALOG = ROOT / "tools" / "capability_map.json"
DEFAULT_OUTPUT = ROOT / "docs" / "TOOL_REFERENCE.md"


def _cell(value: Any) -> str:
    if isinstance(value, list):
        text = ", ".join(str(item) for item in value) or "—"
    else:
        text = str(value or "—")
    return text.replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def render_reference(catalog: dict[str, Any]) -> str:
    if catalog.get("schemaVersion") != 2:
        raise ValueError("capability catalog schemaVersion must be 2")
    tools = catalog.get("tools")
    metadata = catalog.get("toolMetadata")
    profiles = catalog.get("profiles")
    if not isinstance(tools, list) or not isinstance(metadata, dict) or not isinstance(profiles, dict):
        raise ValueError("capability catalog is incomplete")
    if set(tools) != set(metadata):
        raise ValueError("toolMetadata does not match tools")
    lines = [
        "# Generated x64dbg MCP tool reference",
        "",
        "<!-- Generated by tools/generate_tool_reference.py; do not edit by hand. -->",
        "",
        f"- Schema: `{catalog['schemaVersion']}`",
        f"- Registered tools: `{catalog.get('count')}`",
        f"- Compatibility default: `{catalog.get('defaultProfile')}`",
        f"- Recommended facade: `{catalog.get('recommendedProfile')}`",
        "",
        "## Discovery profiles",
        "",
        "| Profile | Tools | Purpose |",
        "|---|---:|---|",
    ]
    for name, value in profiles.items():
        if not isinstance(value, dict):
            raise ValueError(f"profile {name!r} is invalid")
        lines.append(
            f"| `{_cell(name)}` | {int(value.get('count') or 0)} | {_cell(value.get('description'))} |"
        )
    lines.extend(
        [
            "",
            "Profiles only control discovery. They are not an authorization boundary.",
            "",
            "## Tools",
            "",
            "The main table stays intentionally narrow so it remains readable on GitHub "
            "and in narrow MCP documentation panes. Expand a tool for its mutation "
            "surface and conditional effects.",
            "",
            "| Tool | Category | Risk | Discovery profiles |",
            "|---|---|---|---|",
        ]
    )
    operational_details: list[str] = []
    for name in sorted(str(item) for item in tools):
        policy = metadata.get(name)
        if not isinstance(policy, dict):
            raise ValueError(f"metadata for {name!r} is invalid")
        conditional = [
            f"{item.get('kind')} when {item.get('when')}"
            for item in policy.get("conditionalSideEffects", [])
            if isinstance(item, dict)
        ]
        lines.append(
            "| `{}` | `{}` | `{}` | {} |".format(
                _cell(name),
                _cell(policy.get("category")),
                _cell(policy.get("risk")),
                _cell(policy.get("profiles")),
            )
        )
        operational_details.extend(
            [
                "",
                "<details>",
                f"<summary><code>{_cell(name)}</code> operational details</summary>",
                "",
                f"- **Side effects:** {_cell(policy.get('sideEffects'))}",
                f"- **Conditional effects:** {_cell(conditional)}",
                "",
                "</details>",
            ]
        )
    lines.extend(
        [
            "",
            "## Operational details",
            "",
            "Expand a tool below for its declared side effects and conditional effects.",
            "",
            *operational_details,
        ]
    )
    lines.append("")
    return "\n".join(lines)


def _write_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=".tool-reference-", suffix=".tmp", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        temporary = ""
    finally:
        if temporary:
            try:
                os.remove(temporary)
            except OSError:
                pass


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", default=str(DEFAULT_CATALOG))
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        catalog = json.loads(Path(args.catalog).read_text(encoding="utf-8"))
        rendered = render_reference(catalog)
        output = Path(args.output)
        if args.check:
            if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
                print(f"stale generated tool reference: {output}")
                return 1
            print(f"tool reference is current: {output}")
            return 0
        _write_atomic(output, rendered)
        print(f"wrote {output} ({len(catalog.get('tools') or [])} tools)")
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"tool reference generation failed: {exc}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
