#pragma once

#include <cstdint>
#include <functional>
#include <memory>
#include <string>

namespace mcpmutation
{

using Tick = std::uint64_t;
using Clock = std::function<Tick()>;

// The coordinator is a fail-closed state machine.  In particular, a supplied
// lease token is never treated as an unleased request when it is stale,
// expired, or unknown.
enum class Error
{
    None,
    InvalidSession,
    SessionMismatch,
    StaleSessionGeneration,
    InvalidOwner,
    InvalidAcquisitionNonce,
    InvalidLeaseToken,
    InvalidTtl,
    LeaseBusy,
    LeaseRequired,
    UnknownLeaseToken,
    ExpiredLeaseToken,
    StaleLeaseToken,
    OwnerMismatch,
    AcquisitionNonceMismatch,
    StaleLeaseRevision,
    StaleMutationSequence,
    StaleEmergencyEpoch,
    LeaseExpiryPending,
    LeaseReleasePending,
    LeaseSessionInvalidationPending,
    MutationBusy,
    PermitNotActive,
    PermitAlreadyCommitted,
    SessionChanged,
    EmergencyInvalidated,
    ClockFailure,
    ClockRegression,
    CounterExhausted,
};

const char* errorName(Error error) noexcept;

struct SessionIdentity
{
    std::string bridgeInstanceId;
    std::string sessionId;
    std::uint64_t generation = 0;
    std::uint64_t processId = 0;
    std::string targetSha256;

    bool valid() const noexcept;
};

bool operator==(const SessionIdentity& left,
                const SessionIdentity& right) noexcept;
bool operator!=(const SessionIdentity& left,
                const SessionIdentity& right) noexcept;

struct Snapshot
{
    SessionIdentity session;
    std::uint64_t leaseRevision = 0;
    std::uint64_t mutationSeq = 0;
    std::uint64_t emergencyEpoch = 0;
    Tick observedAt = 0;
    Tick leaseExpiresAt = 0;
    std::string leaseOwnerId;
    bool leaseActive = false;
    bool leaseExpiryPending = false;
    bool leaseReleasePending = false;
    bool leaseSessionInvalidationPending = false;
    bool mutationInFlight = false;
};

struct SnapshotResult
{
    Error error = Error::None;
    Snapshot snapshot;

    bool ok() const noexcept { return error == Error::None; }
};

// proposedLeaseToken must be generated by the bridge with a CSPRNG.  Keeping
// generation outside this pure state machine makes tests deterministic and
// prevents user-controlled callbacks from running while the state mutex is
// held.  Both proposedLeaseToken and acquisitionNonce must contain at least
// 32 printable ASCII bytes.
struct AcquireLeaseRequest
{
    SessionIdentity session;
    std::string ownerId;
    std::string acquisitionNonce;
    std::string proposedLeaseToken;
    Tick ttl = 0;
    std::uint64_t expectedLeaseRevision = 0;
};

struct RenewLeaseRequest
{
    SessionIdentity session;
    std::string ownerId;
    std::string acquisitionNonce;
    std::string leaseToken;
    Tick ttl = 0;
    std::uint64_t expectedLeaseRevision = 0;
};

struct ReleaseLeaseRequest
{
    SessionIdentity session;
    std::string ownerId;
    std::string acquisitionNonce;
    std::string leaseToken;
    std::uint64_t expectedLeaseRevision = 0;
};

struct LeaseResult
{
    Error error = Error::None;
    Snapshot snapshot;
    std::string leaseToken;
    Tick expiresAt = 0;
    bool replayed = false;
    bool pending = false;

    bool ok() const noexcept { return error == Error::None; }
};

// Empty lease credentials intentionally request an unleased mutation.  If a
// lease is active, credentials are mandatory.  Supplying any non-empty token
// when no matching lease exists is an explicit error, never a fallback.
struct BeginMutationRequest
{
    SessionIdentity session;
    std::string ownerId;
    std::string acquisitionNonce;
    std::string leaseToken;
    std::uint64_t expectedLeaseRevision = 0;
    std::uint64_t expectedMutationSeq = 0;
    std::uint64_t expectedEmergencyEpoch = 0;
};

struct OperationResult
{
    Error error = Error::None;
    Snapshot snapshot;

    bool ok() const noexcept { return error == Error::None; }
};

struct CommitResult
{
    Error error = Error::None;
    Snapshot snapshot;
    std::uint64_t committedMutationSeq = 0;

    bool ok() const noexcept { return error == Error::None; }
};

namespace detail
{
struct State;
}

// A permit is move-only and pins both the session and lease incarnation.
// Destroying or overwriting an open permit abandons it without advancing
// mutationSeq.  No exception is ever allowed to cross its destructor.
class MutationPermit
{
public:
    MutationPermit() noexcept = default;
    ~MutationPermit() noexcept;

    MutationPermit(MutationPermit&& other) noexcept;
    MutationPermit& operator=(MutationPermit&& other) noexcept;

    MutationPermit(const MutationPermit&) = delete;
    MutationPermit& operator=(const MutationPermit&) = delete;

    bool active() const noexcept;
    CommitResult commit(const SessionIdentity& observedSession);
    void abandon() noexcept;

private:
    friend class MutationCoordinator;

    enum class LocalState
    {
        Empty,
        Open,
        Committed,
        Closed,
    };

    MutationPermit(std::shared_ptr<detail::State> state,
                   std::uint64_t permitId) noexcept;

    std::shared_ptr<detail::State> state_;
    std::uint64_t permitId_ = 0;
    LocalState localState_ = LocalState::Empty;
};

struct BeginMutationResult
{
    Error error = Error::None;
    Snapshot snapshot;
    MutationPermit permit;

    bool ok() const noexcept
    {
        return error == Error::None && permit.active();
    }
};

class MutationCoordinator
{
public:
    MutationCoordinator(SessionIdentity initialSession, Clock clock);
    ~MutationCoordinator() = default;

    MutationCoordinator(const MutationCoordinator&) = delete;
    MutationCoordinator& operator=(const MutationCoordinator&) = delete;
    MutationCoordinator(MutationCoordinator&&) = delete;
    MutationCoordinator& operator=(MutationCoordinator&&) = delete;

    SnapshotResult snapshot();
    LeaseResult acquireLease(const AcquireLeaseRequest& request);
    LeaseResult renewLease(const RenewLeaseRequest& request);
    LeaseResult releaseLease(const ReleaseLeaseRequest& request);
    BeginMutationResult beginMutation(const BeginMutationRequest& request);

    // Emergency invalidation does not pretend that a mutation committed:
    // mutationSeq is unchanged.  It advances a separate epoch so every permit
    // obtained before the emergency action fails its commit.
    OperationResult emergencyInvalidate();

    // Session replacement is authoritative bridge input.  On the same bridge
    // instance its generation must strictly increase.  An in-flight permit
    // pins the obsolete lease until it closes, preventing cross-session
    // handoff; its eventual commit fails with SessionChanged.
    OperationResult replaceSession(const SessionIdentity& newSession);

private:
    std::shared_ptr<detail::State> state_;
};

} // namespace mcpmutation
